# Kafka outgoing channel — DevServices auto-starts Redpanda, no broker URL needed
mp.messaging.outgoing.coffee-orders.connector=smallrye-kafka
mp.messaging.outgoing.coffee-orders.value.serializer=org.apache.kafka.common.serialization.StringSerializer

quarkus.swagger-ui.always-include=true
