# Datasource
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:coffeedb;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Config property — used in GET /menu/info
coffee.shop.name=The Quarkus Cafe
%dev.coffee.shop.name=The Quarkus Cafe (Dev Mode)
%prod.coffee.shop.name=Production Coffee Co
